// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.auvie.engine.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MediaApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class MediaKind(val raw: Int) {
  PHOTO(0),
  VIDEO(1);

  companion object {
    fun ofRaw(raw: Int): MediaKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PickedMedia (
  /** Persisted content:// URI, or a file:// copy when persisting failed. */
  val uri: String,
  val kind: MediaKind,
  /** Size after EXIF / container rotation. */
  val width: Long,
  val height: Long,
  val durationMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PickedMedia {
      val uri = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as MediaKind
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      val durationMs = pigeonVar_list[4] as Long?
      return PickedMedia(uri, kind, width, height, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      kind,
      width,
      height,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PickedMedia
    return MediaApiPigeonUtils.deepEquals(this.uri, other.uri) && MediaApiPigeonUtils.deepEquals(this.kind, other.kind) && MediaApiPigeonUtils.deepEquals(this.width, other.width) && MediaApiPigeonUtils.deepEquals(this.height, other.height) && MediaApiPigeonUtils.deepEquals(this.durationMs, other.durationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.width)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.height)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.durationMs)
    return result
  }
  override fun toString(): String {
    return "PickedMedia(uri=$uri, kind=$kind, width=$width, height=$height, durationMs=$durationMs)"
  }
}

/**
 * Resolved develop parameters: the 12 scalar adjustments (same order as
 * `Adjustment.values`) plus the curve lookup table.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DevelopParams (
  val exposure: Double,
  val brightness: Double,
  val contrast: Double,
  val highlights: Double,
  val shadows: Double,
  val saturation: Double,
  val temperature: Double,
  val tint: Double,
  val sharpen: Double,
  val grain: Double,
  val fade: Double,
  val vignette: Double,
  /** 256×1 RGBA (1024 bytes). */
  val curveLut: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DevelopParams {
      val exposure = pigeonVar_list[0] as Double
      val brightness = pigeonVar_list[1] as Double
      val contrast = pigeonVar_list[2] as Double
      val highlights = pigeonVar_list[3] as Double
      val shadows = pigeonVar_list[4] as Double
      val saturation = pigeonVar_list[5] as Double
      val temperature = pigeonVar_list[6] as Double
      val tint = pigeonVar_list[7] as Double
      val sharpen = pigeonVar_list[8] as Double
      val grain = pigeonVar_list[9] as Double
      val fade = pigeonVar_list[10] as Double
      val vignette = pigeonVar_list[11] as Double
      val curveLut = pigeonVar_list[12] as ByteArray
      return DevelopParams(exposure, brightness, contrast, highlights, shadows, saturation, temperature, tint, sharpen, grain, fade, vignette, curveLut)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exposure,
      brightness,
      contrast,
      highlights,
      shadows,
      saturation,
      temperature,
      tint,
      sharpen,
      grain,
      fade,
      vignette,
      curveLut,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DevelopParams
    return MediaApiPigeonUtils.deepEquals(this.exposure, other.exposure) && MediaApiPigeonUtils.deepEquals(this.brightness, other.brightness) && MediaApiPigeonUtils.deepEquals(this.contrast, other.contrast) && MediaApiPigeonUtils.deepEquals(this.highlights, other.highlights) && MediaApiPigeonUtils.deepEquals(this.shadows, other.shadows) && MediaApiPigeonUtils.deepEquals(this.saturation, other.saturation) && MediaApiPigeonUtils.deepEquals(this.temperature, other.temperature) && MediaApiPigeonUtils.deepEquals(this.tint, other.tint) && MediaApiPigeonUtils.deepEquals(this.sharpen, other.sharpen) && MediaApiPigeonUtils.deepEquals(this.grain, other.grain) && MediaApiPigeonUtils.deepEquals(this.fade, other.fade) && MediaApiPigeonUtils.deepEquals(this.vignette, other.vignette) && MediaApiPigeonUtils.deepEquals(this.curveLut, other.curveLut)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.exposure)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.brightness)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.contrast)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.highlights)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.shadows)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.saturation)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.temperature)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.tint)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.sharpen)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.grain)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.fade)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.vignette)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.curveLut)
    return result
  }
  override fun toString(): String {
    return "DevelopParams(exposure=$exposure, brightness=$brightness, contrast=$contrast, highlights=$highlights, shadows=$shadows, saturation=$saturation, temperature=$temperature, tint=$tint, sharpen=$sharpen, grain=$grain, fade=$fade, vignette=$vignette, curveLut=${curveLut.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreviewInfo (
  val textureId: Long,
  /** Size of the decoded preview image. */
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreviewInfo {
      val textureId = pigeonVar_list[0] as Long
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      return PreviewInfo(textureId, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PreviewInfo
    return MediaApiPigeonUtils.deepEquals(this.textureId, other.textureId) && MediaApiPigeonUtils.deepEquals(this.width, other.width) && MediaApiPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.textureId)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.width)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "PreviewInfo(textureId=$textureId, width=$width, height=$height)"
  }
}
private open class MediaApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PickedMedia.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DevelopParams.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreviewInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MediaKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PickedMedia -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DevelopParams -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PreviewInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MediaHostApi {
  /** Opens the system Photo Picker. Null when the user cancels. */
  suspend fun pickMedia(kind: MediaKind): PickedMedia?
  suspend fun probe(uri: String): PickedMedia
  /** JPEG thumbnail whose longer side is at most [maxPx]. */
  suspend fun thumbnail(uri: String, maxPx: Long): ByteArray
  /** Decodes the photo (longer side ≤ [maxPx]) and shows it in a texture. */
  suspend fun createPhotoPreview(uri: String, maxPx: Long): PreviewInfo
  /** Coalesced: only the latest params are rendered on the next frame. */
  fun updateEdit(textureId: Long, params: DevelopParams)
  fun setShowOriginal(textureId: Long, original: Boolean)
  fun disposePreview(textureId: Long)
  /** Renders offscreen and returns a JPEG whose longer side is ≤ [maxPx]. */
  suspend fun renderPhoto(uri: String, params: DevelopParams, maxPx: Long): ByteArray

  companion object {
    /** The codec used by MediaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MediaApiPigeonCodec()
    }
    /** Sets up an instance of `MediaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MediaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.pickMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val kindArg = args[0] as MediaKind
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.pickMedia(kindArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.probe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.probe(uriArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.thumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val maxPxArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.thumbnail(uriArg, maxPxArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.createPhotoPreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val maxPxArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createPhotoPreview(uriArg, maxPxArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.updateEdit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val paramsArg = args[1] as DevelopParams
            val wrapped: List<Any?> = try {
              api.updateEdit(textureIdArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.setShowOriginal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val originalArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setShowOriginal(textureIdArg, originalArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.disposePreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disposePreview(textureIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.renderPhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val paramsArg = args[1] as DevelopParams
            val maxPxArg = args[2] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.renderPhoto(uriArg, paramsArg, maxPxArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
