// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.auvie.engine.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MediaApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class MediaKind(val raw: Int) {
  PHOTO(0),
  VIDEO(1);

  companion object {
    fun ofRaw(raw: Int): MediaKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ExportFormat(val raw: Int) {
  JPEG(0),
  PNG(1);

  companion object {
    fun ofRaw(raw: Int): ExportFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LayerBlend(val raw: Int) {
  NORMAL(0),
  SCREEN(1),
  MULTIPLY(2),
  OVERLAY(3),
  SOFT_LIGHT(4);

  companion object {
    fun ofRaw(raw: Int): LayerBlend? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PickedMedia (
  /** Persisted content:// URI, or a file:// copy when persisting failed. */
  val uri: String,
  val kind: MediaKind,
  /** Size after EXIF / container rotation. */
  val width: Long,
  val height: Long,
  val durationMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PickedMedia {
      val uri = pigeonVar_list[0] as String
      val kind = pigeonVar_list[1] as MediaKind
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      val durationMs = pigeonVar_list[4] as Long?
      return PickedMedia(uri, kind, width, height, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      kind,
      width,
      height,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PickedMedia
    return MediaApiPigeonUtils.deepEquals(this.uri, other.uri) && MediaApiPigeonUtils.deepEquals(this.kind, other.kind) && MediaApiPigeonUtils.deepEquals(this.width, other.width) && MediaApiPigeonUtils.deepEquals(this.height, other.height) && MediaApiPigeonUtils.deepEquals(this.durationMs, other.durationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.width)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.height)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.durationMs)
    return result
  }
  override fun toString(): String {
    return "PickedMedia(uri=$uri, kind=$kind, width=$width, height=$height, durationMs=$durationMs)"
  }
}

/**
 * Resolved develop parameters: the 12 scalar adjustments (same order as
 * `Adjustment.values`) plus the curve lookup table.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DevelopParams (
  val exposure: Double,
  val brightness: Double,
  val contrast: Double,
  val highlights: Double,
  val shadows: Double,
  val saturation: Double,
  val temperature: Double,
  val tint: Double,
  val sharpen: Double,
  val grain: Double,
  val fade: Double,
  val vignette: Double,
  /** 256×1 RGBA (1024 bytes). */
  val curveLut: ByteArray,
  /**
   * Output uv → source uv as `[a, b, c, d, tx, ty]`
   * (`x' = a·x + b·y + tx`, `y' = c·x + d·y + ty`): crop, turns, flips and
   * straighten (lib/core/models/crop_geometry.dart).
   */
  val geometry: DoubleArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DevelopParams {
      val exposure = pigeonVar_list[0] as Double
      val brightness = pigeonVar_list[1] as Double
      val contrast = pigeonVar_list[2] as Double
      val highlights = pigeonVar_list[3] as Double
      val shadows = pigeonVar_list[4] as Double
      val saturation = pigeonVar_list[5] as Double
      val temperature = pigeonVar_list[6] as Double
      val tint = pigeonVar_list[7] as Double
      val sharpen = pigeonVar_list[8] as Double
      val grain = pigeonVar_list[9] as Double
      val fade = pigeonVar_list[10] as Double
      val vignette = pigeonVar_list[11] as Double
      val curveLut = pigeonVar_list[12] as ByteArray
      val geometry = pigeonVar_list[13] as DoubleArray
      return DevelopParams(exposure, brightness, contrast, highlights, shadows, saturation, temperature, tint, sharpen, grain, fade, vignette, curveLut, geometry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exposure,
      brightness,
      contrast,
      highlights,
      shadows,
      saturation,
      temperature,
      tint,
      sharpen,
      grain,
      fade,
      vignette,
      curveLut,
      geometry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DevelopParams
    return MediaApiPigeonUtils.deepEquals(this.exposure, other.exposure) && MediaApiPigeonUtils.deepEquals(this.brightness, other.brightness) && MediaApiPigeonUtils.deepEquals(this.contrast, other.contrast) && MediaApiPigeonUtils.deepEquals(this.highlights, other.highlights) && MediaApiPigeonUtils.deepEquals(this.shadows, other.shadows) && MediaApiPigeonUtils.deepEquals(this.saturation, other.saturation) && MediaApiPigeonUtils.deepEquals(this.temperature, other.temperature) && MediaApiPigeonUtils.deepEquals(this.tint, other.tint) && MediaApiPigeonUtils.deepEquals(this.sharpen, other.sharpen) && MediaApiPigeonUtils.deepEquals(this.grain, other.grain) && MediaApiPigeonUtils.deepEquals(this.fade, other.fade) && MediaApiPigeonUtils.deepEquals(this.vignette, other.vignette) && MediaApiPigeonUtils.deepEquals(this.curveLut, other.curveLut) && MediaApiPigeonUtils.deepEquals(this.geometry, other.geometry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.exposure)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.brightness)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.contrast)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.highlights)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.shadows)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.saturation)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.temperature)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.tint)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.sharpen)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.grain)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.fade)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.vignette)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.curveLut)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.geometry)
    return result
  }
  override fun toString(): String {
    return "DevelopParams(exposure=$exposure, brightness=$brightness, contrast=$contrast, highlights=$highlights, shadows=$shadows, saturation=$saturation, temperature=$temperature, tint=$tint, sharpen=$sharpen, grain=$grain, fade=$fade, vignette=$vignette, curveLut=${curveLut.contentToString()}, geometry=${geometry.contentToString()})"
  }
}

/**
 * One element rasterized by Flutter (text, brush, sticker, overlay,
 * frame), composited over the developed photo before encoding.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ExportLayer (
  /** PNG file. */
  val path: String,
  /** Where it goes, in output pixels (the PNG is scaled to fit). */
  val left: Double,
  val top: Double,
  val width: Double,
  val height: Double,
  val blend: LayerBlend,
  /** 0…1. */
  val opacity: Double,
  /**
   * Videos: when the layer shows, in ms of the original clip (null =
   * always). Photos ignore them.
   */
  val startMs: Long? = null,
  val endMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExportLayer {
      val path = pigeonVar_list[0] as String
      val left = pigeonVar_list[1] as Double
      val top = pigeonVar_list[2] as Double
      val width = pigeonVar_list[3] as Double
      val height = pigeonVar_list[4] as Double
      val blend = pigeonVar_list[5] as LayerBlend
      val opacity = pigeonVar_list[6] as Double
      val startMs = pigeonVar_list[7] as Long?
      val endMs = pigeonVar_list[8] as Long?
      return ExportLayer(path, left, top, width, height, blend, opacity, startMs, endMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      left,
      top,
      width,
      height,
      blend,
      opacity,
      startMs,
      endMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExportLayer
    return MediaApiPigeonUtils.deepEquals(this.path, other.path) && MediaApiPigeonUtils.deepEquals(this.left, other.left) && MediaApiPigeonUtils.deepEquals(this.top, other.top) && MediaApiPigeonUtils.deepEquals(this.width, other.width) && MediaApiPigeonUtils.deepEquals(this.height, other.height) && MediaApiPigeonUtils.deepEquals(this.blend, other.blend) && MediaApiPigeonUtils.deepEquals(this.opacity, other.opacity) && MediaApiPigeonUtils.deepEquals(this.startMs, other.startMs) && MediaApiPigeonUtils.deepEquals(this.endMs, other.endMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.path)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.left)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.top)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.width)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.height)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.blend)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.opacity)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.startMs)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.endMs)
    return result
  }
  override fun toString(): String {
    return "ExportLayer(path=$path, left=$left, top=$top, width=$width, height=$height, blend=$blend, opacity=$opacity, startMs=$startMs, endMs=$endMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExportRequest (
  val uri: String,
  val params: DevelopParams,
  val format: ExportFormat,
  val outputWidth: Long,
  val outputHeight: Long,
  /** Longer side to decode the original at (enough detail for the crop). */
  val decodeMaxPx: Long,
  /** Copy date, camera and location from the original (JPEG only). */
  val keepMetadata: Boolean,
  /** Without extension. */
  val fileName: String,
  /** Elements in z-order, bottom first. */
  val layers: List<ExportLayer>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExportRequest {
      val uri = pigeonVar_list[0] as String
      val params = pigeonVar_list[1] as DevelopParams
      val format = pigeonVar_list[2] as ExportFormat
      val outputWidth = pigeonVar_list[3] as Long
      val outputHeight = pigeonVar_list[4] as Long
      val decodeMaxPx = pigeonVar_list[5] as Long
      val keepMetadata = pigeonVar_list[6] as Boolean
      val fileName = pigeonVar_list[7] as String
      val layers = pigeonVar_list[8] as List<ExportLayer>
      return ExportRequest(uri, params, format, outputWidth, outputHeight, decodeMaxPx, keepMetadata, fileName, layers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      params,
      format,
      outputWidth,
      outputHeight,
      decodeMaxPx,
      keepMetadata,
      fileName,
      layers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExportRequest
    return MediaApiPigeonUtils.deepEquals(this.uri, other.uri) && MediaApiPigeonUtils.deepEquals(this.params, other.params) && MediaApiPigeonUtils.deepEquals(this.format, other.format) && MediaApiPigeonUtils.deepEquals(this.outputWidth, other.outputWidth) && MediaApiPigeonUtils.deepEquals(this.outputHeight, other.outputHeight) && MediaApiPigeonUtils.deepEquals(this.decodeMaxPx, other.decodeMaxPx) && MediaApiPigeonUtils.deepEquals(this.keepMetadata, other.keepMetadata) && MediaApiPigeonUtils.deepEquals(this.fileName, other.fileName) && MediaApiPigeonUtils.deepEquals(this.layers, other.layers)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.params)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.format)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.outputWidth)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.outputHeight)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.decodeMaxPx)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.keepMetadata)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.fileName)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.layers)
    return result
  }
  override fun toString(): String {
    return "ExportRequest(uri=$uri, params=$params, format=$format, outputWidth=$outputWidth, outputHeight=$outputHeight, decodeMaxPx=$decodeMaxPx, keepMetadata=$keepMetadata, fileName=$fileName, layers=$layers)"
  }
}

/**
 * A video export: develop, crop and scale to [outputWidth]×[outputHeight]
 * (even), keep [trimStartMs]…[trimEndMs] of the original, composite the
 * layers in their time ranges and encode H.264 / AAC MP4.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoExportRequest (
  val uri: String,
  val params: DevelopParams,
  val outputWidth: Long,
  val outputHeight: Long,
  val trimStartMs: Long,
  val trimEndMs: Long,
  val includeAudio: Boolean,
  /** Bits per second. */
  val videoBitrate: Long,
  /** Without extension. */
  val fileName: String,
  /** Elements in z-order, bottom first, with their time ranges. */
  val layers: List<ExportLayer>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoExportRequest {
      val uri = pigeonVar_list[0] as String
      val params = pigeonVar_list[1] as DevelopParams
      val outputWidth = pigeonVar_list[2] as Long
      val outputHeight = pigeonVar_list[3] as Long
      val trimStartMs = pigeonVar_list[4] as Long
      val trimEndMs = pigeonVar_list[5] as Long
      val includeAudio = pigeonVar_list[6] as Boolean
      val videoBitrate = pigeonVar_list[7] as Long
      val fileName = pigeonVar_list[8] as String
      val layers = pigeonVar_list[9] as List<ExportLayer>
      return VideoExportRequest(uri, params, outputWidth, outputHeight, trimStartMs, trimEndMs, includeAudio, videoBitrate, fileName, layers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      params,
      outputWidth,
      outputHeight,
      trimStartMs,
      trimEndMs,
      includeAudio,
      videoBitrate,
      fileName,
      layers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoExportRequest
    return MediaApiPigeonUtils.deepEquals(this.uri, other.uri) && MediaApiPigeonUtils.deepEquals(this.params, other.params) && MediaApiPigeonUtils.deepEquals(this.outputWidth, other.outputWidth) && MediaApiPigeonUtils.deepEquals(this.outputHeight, other.outputHeight) && MediaApiPigeonUtils.deepEquals(this.trimStartMs, other.trimStartMs) && MediaApiPigeonUtils.deepEquals(this.trimEndMs, other.trimEndMs) && MediaApiPigeonUtils.deepEquals(this.includeAudio, other.includeAudio) && MediaApiPigeonUtils.deepEquals(this.videoBitrate, other.videoBitrate) && MediaApiPigeonUtils.deepEquals(this.fileName, other.fileName) && MediaApiPigeonUtils.deepEquals(this.layers, other.layers)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.uri)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.params)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.outputWidth)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.outputHeight)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.trimStartMs)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.trimEndMs)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.includeAudio)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.videoBitrate)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.fileName)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.layers)
    return result
  }
  override fun toString(): String {
    return "VideoExportRequest(uri=$uri, params=$params, outputWidth=$outputWidth, outputHeight=$outputHeight, trimStartMs=$trimStartMs, trimEndMs=$trimEndMs, includeAudio=$includeAudio, videoBitrate=$videoBitrate, fileName=$fileName, layers=$layers)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExportResult (
  /** content:// URI of the copy saved in Pictures/Auvie or Movies/Auvie. */
  val mediaUri: String,
  /** App-private copy, used for sharing. */
  val filePath: String,
  val width: Long,
  val height: Long,
  val bytes: Long,
  /** Videos only. */
  val durationMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExportResult {
      val mediaUri = pigeonVar_list[0] as String
      val filePath = pigeonVar_list[1] as String
      val width = pigeonVar_list[2] as Long
      val height = pigeonVar_list[3] as Long
      val bytes = pigeonVar_list[4] as Long
      val durationMs = pigeonVar_list[5] as Long?
      return ExportResult(mediaUri, filePath, width, height, bytes, durationMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mediaUri,
      filePath,
      width,
      height,
      bytes,
      durationMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExportResult
    return MediaApiPigeonUtils.deepEquals(this.mediaUri, other.mediaUri) && MediaApiPigeonUtils.deepEquals(this.filePath, other.filePath) && MediaApiPigeonUtils.deepEquals(this.width, other.width) && MediaApiPigeonUtils.deepEquals(this.height, other.height) && MediaApiPigeonUtils.deepEquals(this.bytes, other.bytes) && MediaApiPigeonUtils.deepEquals(this.durationMs, other.durationMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.mediaUri)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.filePath)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.width)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.height)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.bytes)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.durationMs)
    return result
  }
  override fun toString(): String {
    return "ExportResult(mediaUri=$mediaUri, filePath=$filePath, width=$width, height=$height, bytes=$bytes, durationMs=$durationMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExportProgress (
  val jobId: String,
  /** 0…1 over the whole export. */
  val fraction: Double,
  /** decode, render, encode or save. */
  val stage: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExportProgress {
      val jobId = pigeonVar_list[0] as String
      val fraction = pigeonVar_list[1] as Double
      val stage = pigeonVar_list[2] as String
      return ExportProgress(jobId, fraction, stage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      jobId,
      fraction,
      stage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExportProgress
    return MediaApiPigeonUtils.deepEquals(this.jobId, other.jobId) && MediaApiPigeonUtils.deepEquals(this.fraction, other.fraction) && MediaApiPigeonUtils.deepEquals(this.stage, other.stage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.jobId)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.fraction)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.stage)
    return result
  }
  override fun toString(): String {
    return "ExportProgress(jobId=$jobId, fraction=$fraction, stage=$stage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreviewInfo (
  val textureId: Long,
  /** Size of the decoded preview image. */
  val width: Long,
  val height: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreviewInfo {
      val textureId = pigeonVar_list[0] as Long
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      return PreviewInfo(textureId, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PreviewInfo
    return MediaApiPigeonUtils.deepEquals(this.textureId, other.textureId) && MediaApiPigeonUtils.deepEquals(this.width, other.width) && MediaApiPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.textureId)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.width)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "PreviewInfo(textureId=$textureId, width=$width, height=$height)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoPreviewInfo (
  val textureId: Long,
  /** Upright size of the video. */
  val width: Long,
  val height: Long,
  val durationMs: Long,
  val hasAudio: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoPreviewInfo {
      val textureId = pigeonVar_list[0] as Long
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val durationMs = pigeonVar_list[3] as Long
      val hasAudio = pigeonVar_list[4] as Boolean
      return VideoPreviewInfo(textureId, width, height, durationMs, hasAudio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      width,
      height,
      durationMs,
      hasAudio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoPreviewInfo
    return MediaApiPigeonUtils.deepEquals(this.textureId, other.textureId) && MediaApiPigeonUtils.deepEquals(this.width, other.width) && MediaApiPigeonUtils.deepEquals(this.height, other.height) && MediaApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MediaApiPigeonUtils.deepEquals(this.hasAudio, other.hasAudio)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.textureId)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.width)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.height)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.hasAudio)
    return result
  }
  override fun toString(): String {
    return "VideoPreviewInfo(textureId=$textureId, width=$width, height=$height, durationMs=$durationMs, hasAudio=$hasAudio)"
  }
}

/**
 * Where a video preview is: sent about 30 times a second while playing,
 * and on every play, pause and seek.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlaybackState (
  val textureId: Long,
  val positionMs: Long,
  val playing: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackState {
      val textureId = pigeonVar_list[0] as Long
      val positionMs = pigeonVar_list[1] as Long
      val playing = pigeonVar_list[2] as Boolean
      return PlaybackState(textureId, positionMs, playing)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      positionMs,
      playing,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlaybackState
    return MediaApiPigeonUtils.deepEquals(this.textureId, other.textureId) && MediaApiPigeonUtils.deepEquals(this.positionMs, other.positionMs) && MediaApiPigeonUtils.deepEquals(this.playing, other.playing)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.textureId)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.positionMs)
    result = 31 * result + MediaApiPigeonUtils.deepHash(this.playing)
    return result
  }
  override fun toString(): String {
    return "PlaybackState(textureId=$textureId, positionMs=$positionMs, playing=$playing)"
  }
}
private open class MediaApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MediaKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ExportFormat.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LayerBlend.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PickedMedia.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DevelopParams.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExportLayer.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExportRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoExportRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExportResult.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExportProgress.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreviewInfo.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoPreviewInfo.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackState.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MediaKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ExportFormat -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is LayerBlend -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PickedMedia -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is DevelopParams -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ExportLayer -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ExportRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is VideoExportRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ExportResult -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ExportProgress -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is PreviewInfo -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is VideoPreviewInfo -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is PlaybackState -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MediaApiPigeonMethodCodec = StandardMethodCodec(MediaApiPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MediaHostApi {
  /** Opens the system Photo Picker. Null when the user cancels. */
  suspend fun pickMedia(kind: MediaKind): PickedMedia?
  suspend fun probe(uri: String): PickedMedia
  /** JPEG thumbnail whose longer side is at most [maxPx]. */
  suspend fun thumbnail(uri: String, maxPx: Long): ByteArray
  /** Decodes the photo (longer side ≤ [maxPx]) and shows it in a texture. */
  suspend fun createPhotoPreview(uri: String, maxPx: Long): PreviewInfo
  /**
   * Opens the video paused at its first frame, shown in a texture rendered
   * at most [maxPx] on the longer side. The texture works with
   * [updateEdit], [setShowOriginal], [resizePreview] and [disposePreview].
   */
  suspend fun createVideoPreview(uri: String, maxPx: Long): VideoPreviewInfo
  fun playVideo(textureId: Long)
  fun pauseVideo(textureId: Long)
  /** [exact] false seeks to the nearest key frame (fast, for scrubbing). */
  fun seekVideo(textureId: Long, positionMs: Long, exact: Boolean)
  /** Playback loops inside [startMs]…[endMs] (the trim). */
  fun setPlaybackRange(textureId: Long, startMs: Long, endMs: Long)
  fun setVideoMuted(textureId: Long, muted: Boolean)
  /** [count] JPEG frames evenly spread over the video, longer side ≤ [maxPx]. */
  suspend fun videoFrames(uri: String, count: Long, maxPx: Long): List<ByteArray>
  /**
   * Peak level (0…1) of the sound in each of [buckets] equal slices. Null
   * when the video has no sound.
   */
  suspend fun waveform(uri: String, buckets: Long): DoubleArray?
  /** Coalesced: only the latest params are rendered on the next frame. */
  fun updateEdit(textureId: Long, params: DevelopParams)
  fun setShowOriginal(textureId: Long, original: Boolean)
  fun disposePreview(textureId: Long)
  /** Sets the preview's pixel size (when the crop's aspect or layout change). */
  fun resizePreview(textureId: Long, width: Long, height: Long)
  /**
   * Renders offscreen and returns a JPEG whose longer side is ≤ [maxPx]:
   * the photo, or the video's frame at [timeMs].
   */
  suspend fun renderFrame(uri: String, params: DevelopParams, maxPx: Long, timeMs: Long?): ByteArray
  /** Free bytes where exports are written. */
  fun availableBytes(): Long
  /**
   * Develops at full size, saves to Pictures/Auvie and keeps an app copy.
   * Progress arrives on [ExportEvents.exportProgress] under [jobId].
   */
  suspend fun exportPhoto(jobId: String, request: ExportRequest): ExportResult
  /**
   * Exports in a background job with a progress notification, saves to
   * Movies/Auvie and keeps an app copy. Progress arrives like photos'.
   */
  suspend fun exportVideo(jobId: String, request: VideoExportRequest): ExportResult
  /** Photos and videos. */
  fun cancelExport(jobId: String)
  /** Asks to show notifications (Android 13+). True when allowed. */
  suspend fun requestNotificationPermission(): Boolean
  /** Puts the saved image on the clipboard. */
  suspend fun copyToClipboard(mediaUri: String)

  companion object {
    /** The codec used by MediaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MediaApiPigeonCodec()
    }
    /** Sets up an instance of `MediaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MediaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.pickMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val kindArg = args[0] as MediaKind
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.pickMedia(kindArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.probe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.probe(uriArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.thumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val maxPxArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.thumbnail(uriArg, maxPxArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.createPhotoPreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val maxPxArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createPhotoPreview(uriArg, maxPxArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.createVideoPreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val maxPxArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.createVideoPreview(uriArg, maxPxArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.playVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.playVideo(textureIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.pauseVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.pauseVideo(textureIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.seekVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val positionMsArg = args[1] as Long
            val exactArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.seekVideo(textureIdArg, positionMsArg, exactArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.setPlaybackRange$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val startMsArg = args[1] as Long
            val endMsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.setPlaybackRange(textureIdArg, startMsArg, endMsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.setVideoMuted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val mutedArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setVideoMuted(textureIdArg, mutedArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.videoFrames$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val countArg = args[1] as Long
            val maxPxArg = args[2] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.videoFrames(uriArg, countArg, maxPxArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.waveform$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val bucketsArg = args[1] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.waveform(uriArg, bucketsArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.updateEdit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val paramsArg = args[1] as DevelopParams
            val wrapped: List<Any?> = try {
              api.updateEdit(textureIdArg, paramsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.setShowOriginal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val originalArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setShowOriginal(textureIdArg, originalArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.disposePreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.disposePreview(textureIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.resizePreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val widthArg = args[1] as Long
            val heightArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.resizePreview(textureIdArg, widthArg, heightArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.renderFrame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            val paramsArg = args[1] as DevelopParams
            val maxPxArg = args[2] as Long
            val timeMsArg = args[3] as Long?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.renderFrame(uriArg, paramsArg, maxPxArg, timeMsArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.availableBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.availableBytes())
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.exportPhoto$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            val requestArg = args[1] as ExportRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.exportPhoto(jobIdArg, requestArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.exportVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            val requestArg = args[1] as VideoExportRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.exportVideo(jobIdArg, requestArg))
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.cancelExport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelExport(jobIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestNotificationPermission())
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.auvie.MediaHostApi.copyToClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaUriArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.copyToClipboard(mediaUriArg)
                listOf(null)
              } catch (exception: Throwable) {
                MediaApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MediaApiPigeonStreamHandler<T>(
    val wrapper: MediaApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MediaApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class ExportProgressStreamHandler : MediaApiPigeonEventChannelWrapper<ExportProgress> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: ExportProgressStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.auvie.ExportEvents.exportProgress"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MediaApiPigeonStreamHandler<ExportProgress>(streamHandler)
      EventChannel(messenger, channelName, MediaApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MediaApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<ExportProgress>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class PlaybackStateStreamHandler : MediaApiPigeonEventChannelWrapper<PlaybackState> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: PlaybackStateStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.auvie.ExportEvents.playbackState"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MediaApiPigeonStreamHandler<PlaybackState>(streamHandler)
      EventChannel(messenger, channelName, MediaApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MediaApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<PlaybackState>) {}

override fun onCancel(p0: Any?) {}
}
      
