// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum MediaKind { photo, video }

class PickedMedia {
  PickedMedia({
    required this.uri,
    required this.kind,
    required this.width,
    required this.height,
    this.durationMs,
  });

  /// Persisted content:// URI, or a file:// copy when persisting failed.
  String uri;

  MediaKind kind;

  /// Size after EXIF / container rotation.
  int width;

  int height;

  int? durationMs;

  List<Object?> _toList() {
    return <Object?>[uri, kind, width, height, durationMs];
  }

  Object encode() {
    return _toList();
  }

  static PickedMedia decode(Object result) {
    result as List<Object?>;
    return PickedMedia(
      uri: result[0]! as String,
      kind: result[1]! as MediaKind,
      width: result[2]! as int,
      height: result[3]! as int,
      durationMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PickedMedia || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(durationMs, other.durationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PickedMedia(uri: $uri, kind: $kind, width: $width, height: $height, durationMs: $durationMs)';
  }
}

/// Resolved develop parameters: the 12 scalar adjustments (same order as
/// `Adjustment.values`) plus the curve lookup table.
class DevelopParams {
  DevelopParams({
    required this.exposure,
    required this.brightness,
    required this.contrast,
    required this.highlights,
    required this.shadows,
    required this.saturation,
    required this.temperature,
    required this.tint,
    required this.sharpen,
    required this.grain,
    required this.fade,
    required this.vignette,
    required this.curveLut,
  });

  double exposure;

  double brightness;

  double contrast;

  double highlights;

  double shadows;

  double saturation;

  double temperature;

  double tint;

  double sharpen;

  double grain;

  double fade;

  double vignette;

  /// 256×1 RGBA (1024 bytes).
  Uint8List curveLut;

  List<Object?> _toList() {
    return <Object?>[
      exposure,
      brightness,
      contrast,
      highlights,
      shadows,
      saturation,
      temperature,
      tint,
      sharpen,
      grain,
      fade,
      vignette,
      curveLut,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DevelopParams decode(Object result) {
    result as List<Object?>;
    return DevelopParams(
      exposure: result[0]! as double,
      brightness: result[1]! as double,
      contrast: result[2]! as double,
      highlights: result[3]! as double,
      shadows: result[4]! as double,
      saturation: result[5]! as double,
      temperature: result[6]! as double,
      tint: result[7]! as double,
      sharpen: result[8]! as double,
      grain: result[9]! as double,
      fade: result[10]! as double,
      vignette: result[11]! as double,
      curveLut: result[12]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DevelopParams || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(exposure, other.exposure) &&
        _deepEquals(brightness, other.brightness) &&
        _deepEquals(contrast, other.contrast) &&
        _deepEquals(highlights, other.highlights) &&
        _deepEquals(shadows, other.shadows) &&
        _deepEquals(saturation, other.saturation) &&
        _deepEquals(temperature, other.temperature) &&
        _deepEquals(tint, other.tint) &&
        _deepEquals(sharpen, other.sharpen) &&
        _deepEquals(grain, other.grain) &&
        _deepEquals(fade, other.fade) &&
        _deepEquals(vignette, other.vignette) &&
        _deepEquals(curveLut, other.curveLut);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DevelopParams(exposure: $exposure, brightness: $brightness, contrast: $contrast, highlights: $highlights, shadows: $shadows, saturation: $saturation, temperature: $temperature, tint: $tint, sharpen: $sharpen, grain: $grain, fade: $fade, vignette: $vignette, curveLut: $curveLut)';
  }
}

class PreviewInfo {
  PreviewInfo({
    required this.textureId,
    required this.width,
    required this.height,
  });

  int textureId;

  /// Size of the decoded preview image.
  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[textureId, width, height];
  }

  Object encode() {
    return _toList();
  }

  static PreviewInfo decode(Object result) {
    result as List<Object?>;
    return PreviewInfo(
      textureId: result[0]! as int,
      width: result[1]! as int,
      height: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreviewInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textureId, other.textureId) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PreviewInfo(textureId: $textureId, width: $width, height: $height)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is MediaKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PickedMedia) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is DevelopParams) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PreviewInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaKind.values[value];
      case 130:
        return PickedMedia.decode(readValue(buffer)!);
      case 131:
        return DevelopParams.decode(readValue(buffer)!);
      case 132:
        return PreviewInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MediaHostApi {
  /// Constructor for [MediaHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MediaHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Opens the system Photo Picker. Null when the user cancels.
  Future<PickedMedia?> pickMedia(MediaKind kind) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.pickMedia$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[kind],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as PickedMedia?;
  }

  Future<PickedMedia> probe(String uri) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PickedMedia;
  }

  /// JPEG thumbnail whose longer side is at most [maxPx].
  Future<Uint8List> thumbnail(String uri, int maxPx) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.thumbnail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, maxPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Decodes the photo (longer side ≤ [maxPx]) and shows it in a texture.
  Future<PreviewInfo> createPhotoPreview(String uri, int maxPx) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.createPhotoPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, maxPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PreviewInfo;
  }

  /// Coalesced: only the latest params are rendered on the next frame.
  Future<void> updateEdit(int textureId, DevelopParams params) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.updateEdit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, params],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setShowOriginal(int textureId, bool original) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.setShowOriginal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, original],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disposePreview(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.disposePreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Renders offscreen and returns a JPEG whose longer side is ≤ [maxPx].
  Future<Uint8List> renderPhoto(
    String uri,
    DevelopParams params,
    int maxPx,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.renderPhoto$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, params, maxPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }
}
