// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum MediaKind { photo, video }

enum ExportFormat { jpeg, png }

enum LayerBlend { normal, screen, multiply, overlay, softLight }

class PickedMedia {
  PickedMedia({
    required this.uri,
    required this.kind,
    required this.width,
    required this.height,
    this.durationMs,
  });

  /// Persisted content:// URI, or a file:// copy when persisting failed.
  String uri;

  MediaKind kind;

  /// Size after EXIF / container rotation.
  int width;

  int height;

  int? durationMs;

  List<Object?> _toList() {
    return <Object?>[uri, kind, width, height, durationMs];
  }

  Object encode() {
    return _toList();
  }

  static PickedMedia decode(Object result) {
    result as List<Object?>;
    return PickedMedia(
      uri: result[0]! as String,
      kind: result[1]! as MediaKind,
      width: result[2]! as int,
      height: result[3]! as int,
      durationMs: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PickedMedia || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(durationMs, other.durationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PickedMedia(uri: $uri, kind: $kind, width: $width, height: $height, durationMs: $durationMs)';
  }
}

/// Resolved develop parameters: the 12 scalar adjustments (same order as
/// `Adjustment.values`) plus the curve lookup table.
class DevelopParams {
  DevelopParams({
    required this.exposure,
    required this.brightness,
    required this.contrast,
    required this.highlights,
    required this.shadows,
    required this.saturation,
    required this.temperature,
    required this.tint,
    required this.sharpen,
    required this.grain,
    required this.fade,
    required this.vignette,
    required this.curveLut,
    required this.geometry,
  });

  double exposure;

  double brightness;

  double contrast;

  double highlights;

  double shadows;

  double saturation;

  double temperature;

  double tint;

  double sharpen;

  double grain;

  double fade;

  double vignette;

  /// 256×1 RGBA (1024 bytes).
  Uint8List curveLut;

  /// Output uv → source uv as `[a, b, c, d, tx, ty]`
  /// (`x' = a·x + b·y + tx`, `y' = c·x + d·y + ty`): crop, turns, flips and
  /// straighten (lib/core/models/crop_geometry.dart).
  Float64List geometry;

  List<Object?> _toList() {
    return <Object?>[
      exposure,
      brightness,
      contrast,
      highlights,
      shadows,
      saturation,
      temperature,
      tint,
      sharpen,
      grain,
      fade,
      vignette,
      curveLut,
      geometry,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DevelopParams decode(Object result) {
    result as List<Object?>;
    return DevelopParams(
      exposure: result[0]! as double,
      brightness: result[1]! as double,
      contrast: result[2]! as double,
      highlights: result[3]! as double,
      shadows: result[4]! as double,
      saturation: result[5]! as double,
      temperature: result[6]! as double,
      tint: result[7]! as double,
      sharpen: result[8]! as double,
      grain: result[9]! as double,
      fade: result[10]! as double,
      vignette: result[11]! as double,
      curveLut: result[12]! as Uint8List,
      geometry: result[13]! as Float64List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DevelopParams || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(exposure, other.exposure) &&
        _deepEquals(brightness, other.brightness) &&
        _deepEquals(contrast, other.contrast) &&
        _deepEquals(highlights, other.highlights) &&
        _deepEquals(shadows, other.shadows) &&
        _deepEquals(saturation, other.saturation) &&
        _deepEquals(temperature, other.temperature) &&
        _deepEquals(tint, other.tint) &&
        _deepEquals(sharpen, other.sharpen) &&
        _deepEquals(grain, other.grain) &&
        _deepEquals(fade, other.fade) &&
        _deepEquals(vignette, other.vignette) &&
        _deepEquals(curveLut, other.curveLut) &&
        _deepEquals(geometry, other.geometry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DevelopParams(exposure: $exposure, brightness: $brightness, contrast: $contrast, highlights: $highlights, shadows: $shadows, saturation: $saturation, temperature: $temperature, tint: $tint, sharpen: $sharpen, grain: $grain, fade: $fade, vignette: $vignette, curveLut: $curveLut, geometry: $geometry)';
  }
}

/// One element rasterized by Flutter (text, brush, sticker, overlay,
/// frame), composited over the developed photo before encoding.
class ExportLayer {
  ExportLayer({
    required this.path,
    required this.left,
    required this.top,
    required this.width,
    required this.height,
    required this.blend,
    required this.opacity,
    this.startMs,
    this.endMs,
  });

  /// PNG file.
  String path;

  /// Where it goes, in output pixels (the PNG is scaled to fit).
  double left;

  double top;

  double width;

  double height;

  LayerBlend blend;

  /// 0…1.
  double opacity;

  /// Videos: when the layer shows, in ms of the original clip (null =
  /// always). Photos ignore them.
  int? startMs;

  int? endMs;

  List<Object?> _toList() {
    return <Object?>[
      path,
      left,
      top,
      width,
      height,
      blend,
      opacity,
      startMs,
      endMs,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExportLayer decode(Object result) {
    result as List<Object?>;
    return ExportLayer(
      path: result[0]! as String,
      left: result[1]! as double,
      top: result[2]! as double,
      width: result[3]! as double,
      height: result[4]! as double,
      blend: result[5]! as LayerBlend,
      opacity: result[6]! as double,
      startMs: result[7] as int?,
      endMs: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExportLayer || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(blend, other.blend) &&
        _deepEquals(opacity, other.opacity) &&
        _deepEquals(startMs, other.startMs) &&
        _deepEquals(endMs, other.endMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExportLayer(path: $path, left: $left, top: $top, width: $width, height: $height, blend: $blend, opacity: $opacity, startMs: $startMs, endMs: $endMs)';
  }
}

class ExportRequest {
  ExportRequest({
    required this.uri,
    required this.params,
    required this.format,
    required this.outputWidth,
    required this.outputHeight,
    required this.decodeMaxPx,
    required this.keepMetadata,
    required this.fileName,
    required this.layers,
  });

  String uri;

  DevelopParams params;

  ExportFormat format;

  int outputWidth;

  int outputHeight;

  /// Longer side to decode the original at (enough detail for the crop).
  int decodeMaxPx;

  /// Copy date, camera and location from the original (JPEG only).
  bool keepMetadata;

  /// Without extension.
  String fileName;

  /// Elements in z-order, bottom first.
  List<ExportLayer> layers;

  List<Object?> _toList() {
    return <Object?>[
      uri,
      params,
      format,
      outputWidth,
      outputHeight,
      decodeMaxPx,
      keepMetadata,
      fileName,
      layers,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ExportRequest decode(Object result) {
    result as List<Object?>;
    return ExportRequest(
      uri: result[0]! as String,
      params: result[1]! as DevelopParams,
      format: result[2]! as ExportFormat,
      outputWidth: result[3]! as int,
      outputHeight: result[4]! as int,
      decodeMaxPx: result[5]! as int,
      keepMetadata: result[6]! as bool,
      fileName: result[7]! as String,
      layers: (result[8]! as List<Object?>).cast<ExportLayer>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExportRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(params, other.params) &&
        _deepEquals(format, other.format) &&
        _deepEquals(outputWidth, other.outputWidth) &&
        _deepEquals(outputHeight, other.outputHeight) &&
        _deepEquals(decodeMaxPx, other.decodeMaxPx) &&
        _deepEquals(keepMetadata, other.keepMetadata) &&
        _deepEquals(fileName, other.fileName) &&
        _deepEquals(layers, other.layers);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExportRequest(uri: $uri, params: $params, format: $format, outputWidth: $outputWidth, outputHeight: $outputHeight, decodeMaxPx: $decodeMaxPx, keepMetadata: $keepMetadata, fileName: $fileName, layers: $layers)';
  }
}

/// A video export: develop, crop and scale to [outputWidth]×[outputHeight]
/// (even), keep [trimStartMs]…[trimEndMs] of the original, composite the
/// layers in their time ranges and encode H.264 / AAC MP4.
class VideoExportRequest {
  VideoExportRequest({
    required this.uri,
    required this.params,
    required this.outputWidth,
    required this.outputHeight,
    required this.trimStartMs,
    required this.trimEndMs,
    required this.includeAudio,
    required this.videoBitrate,
    required this.fileName,
    required this.layers,
  });

  String uri;

  DevelopParams params;

  int outputWidth;

  int outputHeight;

  int trimStartMs;

  int trimEndMs;

  bool includeAudio;

  /// Bits per second.
  int videoBitrate;

  /// Without extension.
  String fileName;

  /// Elements in z-order, bottom first, with their time ranges.
  List<ExportLayer> layers;

  List<Object?> _toList() {
    return <Object?>[
      uri,
      params,
      outputWidth,
      outputHeight,
      trimStartMs,
      trimEndMs,
      includeAudio,
      videoBitrate,
      fileName,
      layers,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VideoExportRequest decode(Object result) {
    result as List<Object?>;
    return VideoExportRequest(
      uri: result[0]! as String,
      params: result[1]! as DevelopParams,
      outputWidth: result[2]! as int,
      outputHeight: result[3]! as int,
      trimStartMs: result[4]! as int,
      trimEndMs: result[5]! as int,
      includeAudio: result[6]! as bool,
      videoBitrate: result[7]! as int,
      fileName: result[8]! as String,
      layers: (result[9]! as List<Object?>).cast<ExportLayer>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoExportRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(params, other.params) &&
        _deepEquals(outputWidth, other.outputWidth) &&
        _deepEquals(outputHeight, other.outputHeight) &&
        _deepEquals(trimStartMs, other.trimStartMs) &&
        _deepEquals(trimEndMs, other.trimEndMs) &&
        _deepEquals(includeAudio, other.includeAudio) &&
        _deepEquals(videoBitrate, other.videoBitrate) &&
        _deepEquals(fileName, other.fileName) &&
        _deepEquals(layers, other.layers);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoExportRequest(uri: $uri, params: $params, outputWidth: $outputWidth, outputHeight: $outputHeight, trimStartMs: $trimStartMs, trimEndMs: $trimEndMs, includeAudio: $includeAudio, videoBitrate: $videoBitrate, fileName: $fileName, layers: $layers)';
  }
}

class ExportResult {
  ExportResult({
    required this.mediaUri,
    required this.filePath,
    required this.width,
    required this.height,
    required this.bytes,
    this.durationMs,
  });

  /// content:// URI of the copy saved in Pictures/Auvie or Movies/Auvie.
  String mediaUri;

  /// App-private copy, used for sharing.
  String filePath;

  int width;

  int height;

  int bytes;

  /// Videos only.
  int? durationMs;

  List<Object?> _toList() {
    return <Object?>[mediaUri, filePath, width, height, bytes, durationMs];
  }

  Object encode() {
    return _toList();
  }

  static ExportResult decode(Object result) {
    result as List<Object?>;
    return ExportResult(
      mediaUri: result[0]! as String,
      filePath: result[1]! as String,
      width: result[2]! as int,
      height: result[3]! as int,
      bytes: result[4]! as int,
      durationMs: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExportResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(mediaUri, other.mediaUri) &&
        _deepEquals(filePath, other.filePath) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(bytes, other.bytes) &&
        _deepEquals(durationMs, other.durationMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExportResult(mediaUri: $mediaUri, filePath: $filePath, width: $width, height: $height, bytes: $bytes, durationMs: $durationMs)';
  }
}

class ExportProgress {
  ExportProgress({
    required this.jobId,
    required this.fraction,
    required this.stage,
  });

  String jobId;

  /// 0…1 over the whole export.
  double fraction;

  /// decode, render, encode or save.
  String stage;

  List<Object?> _toList() {
    return <Object?>[jobId, fraction, stage];
  }

  Object encode() {
    return _toList();
  }

  static ExportProgress decode(Object result) {
    result as List<Object?>;
    return ExportProgress(
      jobId: result[0]! as String,
      fraction: result[1]! as double,
      stage: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExportProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(jobId, other.jobId) &&
        _deepEquals(fraction, other.fraction) &&
        _deepEquals(stage, other.stage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExportProgress(jobId: $jobId, fraction: $fraction, stage: $stage)';
  }
}

class PreviewInfo {
  PreviewInfo({
    required this.textureId,
    required this.width,
    required this.height,
  });

  int textureId;

  /// Size of the decoded preview image.
  int width;

  int height;

  List<Object?> _toList() {
    return <Object?>[textureId, width, height];
  }

  Object encode() {
    return _toList();
  }

  static PreviewInfo decode(Object result) {
    result as List<Object?>;
    return PreviewInfo(
      textureId: result[0]! as int,
      width: result[1]! as int,
      height: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreviewInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textureId, other.textureId) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PreviewInfo(textureId: $textureId, width: $width, height: $height)';
  }
}

class VideoPreviewInfo {
  VideoPreviewInfo({
    required this.textureId,
    required this.width,
    required this.height,
    required this.durationMs,
    required this.hasAudio,
  });

  int textureId;

  /// Upright size of the video.
  int width;

  int height;

  int durationMs;

  bool hasAudio;

  List<Object?> _toList() {
    return <Object?>[textureId, width, height, durationMs, hasAudio];
  }

  Object encode() {
    return _toList();
  }

  static VideoPreviewInfo decode(Object result) {
    result as List<Object?>;
    return VideoPreviewInfo(
      textureId: result[0]! as int,
      width: result[1]! as int,
      height: result[2]! as int,
      durationMs: result[3]! as int,
      hasAudio: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoPreviewInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textureId, other.textureId) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(durationMs, other.durationMs) &&
        _deepEquals(hasAudio, other.hasAudio);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoPreviewInfo(textureId: $textureId, width: $width, height: $height, durationMs: $durationMs, hasAudio: $hasAudio)';
  }
}

/// Where a video preview is: sent about 30 times a second while playing,
/// and on every play, pause and seek.
class PlaybackState {
  PlaybackState({
    required this.textureId,
    required this.positionMs,
    required this.playing,
  });

  int textureId;

  int positionMs;

  bool playing;

  List<Object?> _toList() {
    return <Object?>[textureId, positionMs, playing];
  }

  Object encode() {
    return _toList();
  }

  static PlaybackState decode(Object result) {
    result as List<Object?>;
    return PlaybackState(
      textureId: result[0]! as int,
      positionMs: result[1]! as int,
      playing: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlaybackState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textureId, other.textureId) &&
        _deepEquals(positionMs, other.positionMs) &&
        _deepEquals(playing, other.playing);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlaybackState(textureId: $textureId, positionMs: $positionMs, playing: $playing)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is MediaKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ExportFormat) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is LayerBlend) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PickedMedia) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is DevelopParams) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ExportLayer) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is ExportRequest) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is VideoExportRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ExportResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is ExportProgress) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is PreviewInfo) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is VideoPreviewInfo) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PlaybackState) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ExportFormat.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : LayerBlend.values[value];
      case 132:
        return PickedMedia.decode(readValue(buffer)!);
      case 133:
        return DevelopParams.decode(readValue(buffer)!);
      case 134:
        return ExportLayer.decode(readValue(buffer)!);
      case 135:
        return ExportRequest.decode(readValue(buffer)!);
      case 136:
        return VideoExportRequest.decode(readValue(buffer)!);
      case 137:
        return ExportResult.decode(readValue(buffer)!);
      case 138:
        return ExportProgress.decode(readValue(buffer)!);
      case 139:
        return PreviewInfo.decode(readValue(buffer)!);
      case 140:
        return VideoPreviewInfo.decode(readValue(buffer)!);
      case 141:
        return PlaybackState.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class MediaHostApi {
  /// Constructor for [MediaHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MediaHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Opens the system Photo Picker. Null when the user cancels.
  Future<PickedMedia?> pickMedia(MediaKind kind) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.pickMedia$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[kind],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as PickedMedia?;
  }

  Future<PickedMedia> probe(String uri) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PickedMedia;
  }

  /// JPEG thumbnail whose longer side is at most [maxPx].
  Future<Uint8List> thumbnail(String uri, int maxPx) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.thumbnail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, maxPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Decodes the photo (longer side ≤ [maxPx]) and shows it in a texture.
  Future<PreviewInfo> createPhotoPreview(String uri, int maxPx) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.createPhotoPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, maxPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PreviewInfo;
  }

  /// Opens the video paused at its first frame, shown in a texture rendered
  /// at most [maxPx] on the longer side. The texture works with
  /// [updateEdit], [setShowOriginal], [resizePreview] and [disposePreview].
  Future<VideoPreviewInfo> createVideoPreview(String uri, int maxPx) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.createVideoPreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, maxPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VideoPreviewInfo;
  }

  Future<void> playVideo(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.playVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> pauseVideo(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.pauseVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// [exact] false seeks to the nearest key frame (fast, for scrubbing).
  Future<void> seekVideo(int textureId, int positionMs, bool exact) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.seekVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, positionMs, exact],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Playback loops inside [startMs]…[endMs] (the trim).
  Future<void> setPlaybackRange(int textureId, int startMs, int endMs) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.setPlaybackRange$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, startMs, endMs],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setVideoMuted(int textureId, bool muted) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.setVideoMuted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, muted],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// [count] JPEG frames evenly spread over the video, longer side ≤ [maxPx].
  Future<List<Uint8List>> videoFrames(String uri, int count, int maxPx) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.videoFrames$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, count, maxPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<Uint8List>();
  }

  /// Peak level (0…1) of the sound in each of [buckets] equal slices. Null
  /// when the video has no sound.
  Future<Float64List?> waveform(String uri, int buckets) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.waveform$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, buckets],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as Float64List?;
  }

  /// Coalesced: only the latest params are rendered on the next frame.
  Future<void> updateEdit(int textureId, DevelopParams params) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.updateEdit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, params],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setShowOriginal(int textureId, bool original) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.setShowOriginal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, original],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> disposePreview(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.disposePreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Sets the preview's pixel size (when the crop's aspect or layout change).
  Future<void> resizePreview(int textureId, int width, int height) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.resizePreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, width, height],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Renders offscreen and returns a JPEG whose longer side is ≤ [maxPx]:
  /// the photo, or the video's frame at [timeMs].
  Future<Uint8List> renderFrame(
    String uri,
    DevelopParams params,
    int maxPx,
    int? timeMs,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.renderFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri, params, maxPx, timeMs],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Uint8List;
  }

  /// Free bytes where exports are written.
  Future<int> availableBytes() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.availableBytes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  /// Develops at full size, saves to Pictures/Auvie and keeps an app copy.
  /// Progress arrives on [ExportEvents.exportProgress] under [jobId].
  Future<ExportResult> exportPhoto(String jobId, ExportRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.exportPhoto$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[jobId, request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ExportResult;
  }

  /// Exports in a background job with a progress notification, saves to
  /// Movies/Auvie and keeps an app copy. Progress arrives like photos'.
  Future<ExportResult> exportVideo(
    String jobId,
    VideoExportRequest request,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.exportVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[jobId, request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ExportResult;
  }

  /// Photos and videos.
  Future<void> cancelExport(String jobId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.cancelExport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[jobId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Asks to show notifications (Android 13+). True when allowed.
  Future<bool> requestNotificationPermission() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.requestNotificationPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Puts the saved image on the clipboard.
  Future<void> copyToClipboard(String mediaUri) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.auvie.MediaHostApi.copyToClipboard$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[mediaUri],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Returns a broadcast [Stream] of events from the `exportProgress` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<ExportProgress> exportProgress({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel exportProgressChannel = EventChannel(
    'dev.flutter.pigeon.auvie.ExportEvents.exportProgress$instanceName',
    pigeonMethodCodec,
  );
  return exportProgressChannel.receiveBroadcastStream().map((dynamic event) {
    return event as ExportProgress;
  });
}

/// Returns a broadcast [Stream] of events from the `playbackState` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<PlaybackState> playbackState({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel playbackStateChannel = EventChannel(
    'dev.flutter.pigeon.auvie.ExportEvents.playbackState$instanceName',
    pigeonMethodCodec,
  );
  return playbackStateChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlaybackState;
  });
}
